name: gripable_assignment
description: A reddit clone app created for Gripable assignment.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/config/